name: komodo_dex_server
description: A new Flutter plugin project.
version: 0.0.1
homepage: "https://komodoplatform.com/"

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1
  
flutter:
  plugin:
    platforms:
      android:
        package: com.example.komodo_dex_server
        pluginClass: KomodoDexServerPlugin
      ios:
        pluginClass: KomodoDexServerPlugin